version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.5-astatine
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.5-astatine
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    links:
      - selenium-hub
  firefox:
    image: selenium/node-firefox:3.141.5-astatine
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    links:
      - selenium-hub